# Cluster-wide resources using istio-system.
# This is needed for installing a-la-carte or demo as first step, to create the cluster-wide resources
# and bindings.

# The other steps can be run without cluster-wide permissions, by a service account with permissions only inventory:
# the istio-system namespace.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds-namespace.gen.yaml
  - crd-mixer.yaml
  - istiod.yaml

commonLabels:
  istio: cluster
