apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fortiosds
  labels:
    app: fortiosds-STRESSTESTREPLACEME
spec:
  selector:
    matchLabels:
      app: fortiosds-STRESSTESTREPLACEME
spec:
  template:
    metadata:
      labels:
        app: fortiosds-STRESSTESTREPLACEME
