# The names use 'istiod' prefix, to avoid conflicts with an existing install of istio in istio-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod-ingressgateway
  namespace: istio-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istiod-ingressgateway
  namespace: istio-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istiod-ingressgateway
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istiod-ingressgateway
subjects:
  - kind: ServiceAccount
    name: istiod-ingressgateway

---
